before_install:
    - sudo apt-get -qq update
    - sudo apt-get install google-mock libgtest-dev

script:
    - ./build.sh
    - ./test.sh

after_success: 
    - bash <(curl -s https://codecov.io/bash)
