before_install:
    - sudo apt-get -qq update
    - sudo apt-get install python3-pip ninja
    - sudo pip3 install meson

script:
    - ./build.sh
    - ./test.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
