language: cpp
compiler:
    - g++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test

script:
    - sudo ./install-deps.sh
    - ./build.sh
    - ./test.sh

after_success: 
    - bash <(curl -s https://codecov.io/bash)
