language: cpp
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo ./install-deps.sh

script:
    - ./build.sh
    - ./test.sh

after_success: 
    - bash <(curl -s https://codecov.io/bash)
